"""Prompt templates and builders."""

from .builder import PromptBuilder
from .templates import (
    COMPRESS_CONTEXT_TEMPLATE,
    EXTRACT_ESSENCE_TEMPLATE,
    PROGRESSIVE_COMPRESS_TEMPLATE,
    STYLE_INSTRUCTIONS,
    SUMMARIZE_DIFF_TEMPLATE,
    SUMMARIZE_TEMPLATE,
    SYSTEM_PROMPT,
    UNIFY_SUMMARIES_TEMPLATE,
)

__all__ = [
    "PromptBuilder",
    "SYSTEM_PROMPT",
    "SUMMARIZE_TEMPLATE",
    "COMPRESS_CONTEXT_TEMPLATE",
    "EXTRACT_ESSENCE_TEMPLATE",
    "UNIFY_SUMMARIES_TEMPLATE",
    "SUMMARIZE_DIFF_TEMPLATE",
    "PROGRESSIVE_COMPRESS_TEMPLATE",
    "STYLE_INSTRUCTIONS",
]
